const KDOW=['일','월','화','수','목','금','토'];
const screens={home:document.getElementById('home'),list:document.getElementById('list'),detail:document.getElementById('detail')};
const headerTitle=document.getElementById('headerTitle');
const headerSub=document.getElementById('headerSub');
const backBtn=document.getElementById('backBtn');
let stack=['home'];
let currentSection=null;
const todayStr=new Date().toISOString().slice(0,10);

function dateInfo(dateStr){const d=new Date(dateStr+'T00:00:00');return{m:d.getMonth()+1,day:d.getDate(),dow:KDOW[d.getDay()]};}
function isPast(dateStr){return dateStr<todayStr;}
function isNow(dateStr){const d=new Date(dateStr+'T00:00:00');const t=new Date(todayStr+'T00:00:00');return Math.abs(d-t)<7*86400000;}
function cssVar(color){return{main:`var(--${color})`,bg:`var(--${color}-bg)`,light:`var(--${color}-light)`};}
function setHeader(title='성민교회',sub='예배와 말씀을 한눈에'){headerTitle.textContent=title;headerSub.textContent=sub;backBtn.classList.toggle('visible',stack.length>1);}
function showScreen(name){Object.entries(screens).forEach(([key,el])=>{el.classList.toggle('active',key===name);el.classList.toggle('behind',stack[stack.length-2]===key);});}
function go(name){stack.push(name);showScreen(name);backBtn.classList.toggle('visible',true);}
function back(){if(stack.length<=1)return;const old=stack.pop();screens[old].classList.remove('active');const prev=stack[stack.length-1];showScreen(prev);if(prev==='home')setHeader();else if(prev==='list'&&currentSection){const s=churchData[currentSection];setHeader(`${s.icon} ${s.title}`,s.subtitle);}backBtn.classList.toggle('visible',stack.length>1);}
backBtn.addEventListener('click',back);

function renderHome(){const now=new Date();document.getElementById('home').innerHTML=`<div class="wrap"><div class="hero"><div class="hero-date">${now.getFullYear()}년 ${now.getMonth()+1}월 ${now.getDate()}일</div><div class="hero-title">성민교회</div></div><div class="menu-grid">${menuCard('sunday','card-sun','☀️','주일예배','이번 주 말씀 본문과<br>설교 제목, 담당자','요한복음 강해')}${menuCard('wednesday','card-wed','🕊','수요예배','SBA 성서학 강의 일정과<br>담당자','성서학 과정3')}${menuCard('friday','card-fri','🔥','금요성령집회','본문, 제목, 찬양·PD<br>기도용사 담당자','사무엘상 강해')}${menuCard('qt','card-qt','📖','큐티 본문','월별 부모 페이지로 보는<br>매일 큐티 본문','5–9월')}${menuCard('leaders','card-ldr full','👥','한 주간 예배 담당자','이번 주 새벽·수요·금요 예배를 섬기는 분들','매주 업데이트')}</div><div class="footer-note">v2 구조: 일정 수정은 data.js만 바꾸면 됩니다.</div></div>`;document.querySelectorAll('[data-section]').forEach(btn=>btn.addEventListener('click',()=>renderList(btn.dataset.section)));}
function menuCard(section,cls,icon,title,desc,badge){return`<button class="menu-card ${cls}" type="button" data-section="${section}"><span class="m-icon">${icon}</span><div class="m-title">${title}</div><div class="m-desc">${desc}</div><span class="m-badge">${badge}</span></button>`;}

function renderList(section){currentSection=section;const s=churchData[section];setHeader(`${s.icon} ${s.title}`,s.subtitle);const color=s.color;const c=cssVar(color);let body='';if(section==='leaders')body=renderLeaders();else if(section==='qt')body=renderQtMonthParents(s);else body=s.items.map((item,i)=>renderListItem(section,item,i,color,true)).join('');screens.list.innerHTML=`<div class="wrap"><div class="list-head"><span class="list-icon">${s.icon}</span><h2 class="list-title color-${color}">${s.title}</h2><div class="list-desc">${s.description}</div></div>${section==='leaders'?'':(s.theme?`<div class="theme-box" style="border-color:${c.main}">${s.theme}</div>`:'')}${body}</div>`;screens.list.querySelectorAll('[data-index]').forEach(el=>el.addEventListener('click',()=>renderDetail(section,Number(el.dataset.index))));screens.list.querySelectorAll('[data-month]').forEach(el=>el.addEventListener('click',()=>renderQtMonthDetail(Number(el.dataset.month))));go('list');}

function getQtGroups(sectionData=churchData.qt){const groups={};sectionData.items.forEach((item,index)=>{const month=Number(item.date.slice(5,7));if(!groups[month])groups[month]=[];groups[month].push({item,index});});return groups;}
function renderQtMonthParents(sectionData){const groups=getQtGroups(sectionData);return Object.keys(groups).map(monthKey=>{const month=Number(monthKey);const summary=sectionData.months?.[month]||'';const count=groups[month].length;return`<div class="svc-item color-qt" data-month="${month}"><div class="svc-date"><div class="svc-m">2026</div><div class="svc-d">${month}</div><div class="svc-w">월</div></div><div class="svc-body"><div class="svc-title">2026년 ${month}월 큐티 본문</div><div class="svc-passage">📖 ${summary||'월별 큐티 본문'}</div><div class="svc-extra">전체 ${count}개 본문 보기</div></div><div class="svc-arr">›</div></div>`;}).join('');}
function renderQtMonthDetail(month){const s=churchData.qt;const groups=getQtGroups(s);const rows=(groups[month]||[]).map(({item})=>renderQtDayRow(item)).join('');const summary=s.months?.[month]||'';setHeader(`📖 2026년 ${month}월 큐티`,summary||'월별 큐티 본문');screens.detail.innerHTML=`<div class="wrap"><div class="list-head"><span class="list-icon">📖</span><h2 class="list-title color-qt">2026년 ${month}월 큐티 본문</h2><div class="list-desc">${summary}</div></div><div class="theme-box" style="border-color:var(--qt)">월별 전체 본문입니다. 날짜별 본문과 제목을 한 화면에서 확인할 수 있습니다.</div>${rows}</div>`;go('detail');}
function renderQtDayRow(item){const {m,day,dow}=dateInfo(item.date);const now=isNow(item.date);const past=isPast(item.date)&&!now;const title=item.title||item.passage;return`<div class="svc-item color-qt ${now?'now':''} ${past?'past':''}"><div class="svc-date"><div class="svc-m">${m}월</div><div class="svc-d">${day}</div><div class="svc-w">${dow}요일</div></div><div class="svc-body"><div class="svc-title">${title}</div><div class="svc-passage">📖 ${item.passage}</div></div></div>`;}
function renderListItem(section,item,i,color,clickable=true){const {m,day,dow}=dateInfo(item.date);const now=isNow(item.date);const past=isPast(item.date)&&!now;const title=item.title||item.subject||item.passage;const passage=item.passage||item.subject||'';const extra=section==='sunday'?`#${item.week}주차`:section==='wednesday'?`${item.preacher} · ${item.worship}`:section==='friday'?(item.preacher?`강사 ${item.preacher}`:`찬양 ${item.worship}`):'';return`<div class="svc-item color-${color} ${now?'now':''} ${past?'past':''}" ${clickable?`data-index="${i}"`:''}><div class="svc-date"><div class="svc-m">${m}월</div><div class="svc-d">${day}</div><div class="svc-w">${dow}요일</div></div><div class="svc-body"><div class="svc-title">${title}${now?`<span class="now-badge" style="background:var(--${color}-bg);color:var(--${color})">이번주</span>`:''}</div><div class="svc-passage">📖 ${passage}</div>${extra?`<div class="svc-extra">${extra}</div>`:''}</div>${clickable?'<div class="svc-arr">›</div>':''}</div>`;}

function renderDetail(section,index){const s=churchData[section];const item=s.items[index];const color=s.color;const c=cssVar(color);const {m,day,dow}=dateInfo(item.date);setHeader(item.title||item.subject||item.passage,`${m}월 ${day}일 ${dow}요일`);screens.detail.innerHTML=`<div class="wrap"><div class="detail-hero" style="border-top-color:${c.main}"><div class="detail-date">${m}월 ${day}일 (${dow}) ${item.lec?item.lec+'강':''}</div><div class="detail-title">${item.title||item.subject||item.passage}</div><span class="pill" style="background:${c.bg};color:${c.main};border-color:${c.light}">📖 ${item.passage||item.subject}</span></div>${renderStaff(section,item,color)}</div>`;go('detail');}
function renderStaff(section,item,color){if(section==='qt')return'';if(section==='sunday'){if(!item.staff)return`<div class="detail-sec"><div class="sec-label">예배 담당자</div><div class="s-name" style="text-align:left;color:var(--soft)">담당자 정보가 준비되지 않았습니다.</div></div>`;return staffBox('예배 담당자',Object.entries(item.staff));}if(section==='wednesday'){return staffBox('예배 담당자',[['설교',item.preacher],['찬양',item.worship],['음향',item.sound],['PD',item.pd]]);}if(section==='friday'){const rows=[];if(item.preacher)rows.push(['강사',item.preacher]);rows.push(['찬양',item.worship],['PD',item.pd],['자막',item.caption]);const tags=(item.prayer||[]).map(p=>`<span class="tag">${p}</span>`).join('');return`${staffBox('예배 담당자',rows)}<div class="detail-sec"><div class="sec-label">기도용사</div><div class="tag-row">${tags}</div></div>`;}return'';}
function staffBox(label,rows){return`<div class="detail-sec"><div class="sec-label">${label}</div>${rows.map(([r,n])=>`<div class="staff-row"><span class="s-role">${r}</span><span class="s-name">${n}</span></div>`).join('')}</div>`;}
function renderLeaders(){
  const L=churchData.leaders;
  const parts=L.week.split(' — ');
  const [sm,sd]=parts[0].split('/').map(Number);
  const [em,ed]=parts[1].split('/').map(Number);
  const year=new Date().getFullYear();
  const startDate=new Date(year,sm-1,sd);
  const weekLabel=sm===em?`${year}년 ${sm}월 ${sd}일 — ${ed}일`:`${year}년 ${sm}월 ${sd}일 — ${em}월 ${ed}일`;
  const chipP=name=>`<span class="ldr2-chip ${name==='목사님'?'ldr2-chip-pastor':'ldr2-chip-sermon'}">${name}</span>`;
  const dayHeaders=L.dawn.days.map((d,i)=>{const dt=new Date(startDate);dt.setDate(sd+i);return`<th>${d}<small>${dt.getDate()}일</small></th>`;}).join('');
  const pRow=L.dawn.preacher.map(v=>`<td>${chipP(v)}</td>`).join('');
  const cRow=L.dawn.caption.map(v=>`<td><span class="ldr2-chip ldr2-chip-sub">${v}</span></td>`).join('');
  const aRow=L.dawn.accomp.map(v=>`<td><span class="ldr2-chip ldr2-chip-plain">${v}</span></td>`).join('');
  const pTags=L.friday.prayer.map(p=>`<span class="ldr2-prayer-tag">${p}</span>`).join('');
  const fridayPreacher=L.friday.preacher?`<div class="ldr2-role-row"><span class="ldr2-role-tag">강사</span><span class="ldr2-role-val">${L.friday.preacher}</span></div>`:'';
  return`<div class="ldr2-wrap"><div class="ldr2-date-row"><span class="ldr2-date-sticker">🗓 ${weekLabel}</span></div><div class="ldr2-card"><div class="ldr2-sec-head"><div class="ldr2-sec-icon green">🌅</div><span class="ldr2-sec-title">새벽기도회 담당</span><span class="ldr2-sec-badge green">${L.week}</span></div><table class="ldr2-dawn-table"><thead><tr><th style="width:34px"></th>${dayHeaders}</tr></thead><tbody><tr><td><span class="ldr2-row-label">설교</span></td>${pRow}</tr><tr><td><span class="ldr2-row-label">자막</span></td>${cRow}</tr><tr><td><span class="ldr2-row-label">반주</span></td>${aRow}</tr></tbody></table></div><div class="ldr2-divider">🍃 🌿 🍃</div><div class="ldr2-worship-grid"><div class="ldr2-worship-card"><div class="ldr2-worship-head wed"><div class="ldr2-worship-icon">🕊️</div><div class="ldr2-worship-title">수요예배</div><div class="ldr2-worship-date">${L.wednesday.date}</div></div><div class="ldr2-worship-body"><div class="ldr2-role-row"><span class="ldr2-role-tag">설교</span><span class="ldr2-role-val">${L.wednesday.preacher}</span></div><div class="ldr2-role-row"><span class="ldr2-role-tag">찬양</span><span class="ldr2-role-val">${L.wednesday.worship}</span></div><div class="ldr2-role-row"><span class="ldr2-role-tag">음향</span><span class="ldr2-role-val">${L.wednesday.sound}</span></div><div class="ldr2-role-row"><span class="ldr2-role-tag">PD</span><span class="ldr2-role-val">${L.wednesday.pd}</span></div></div></div><div class="ldr2-worship-card"><div class="ldr2-worship-head fri"><div class="ldr2-worship-icon">🔥</div><div class="ldr2-worship-title">금요성령집회</div><div class="ldr2-worship-date">${L.friday.date}</div></div><div class="ldr2-worship-body">${fridayPreacher}<div class="ldr2-role-row"><span class="ldr2-role-tag">찬양</span><span class="ldr2-role-val">${L.friday.worship}</span></div><div class="ldr2-role-row"><span class="ldr2-role-tag">PD</span><span class="ldr2-role-val">${L.friday.pd}</span></div><div class="ldr2-role-row"><span class="ldr2-role-tag">자막</span><span class="ldr2-role-val">${L.friday.caption}</span></div></div><div class="ldr2-prayer-box"><div class="ldr2-prayer-title">기도용사</div><div class="ldr2-prayer-tags">${pTags}</div></div></div></div><div class="ldr2-footer">사랑과 은혜가 넘치는 공동체<br>은혜로운 한 주간 되세요 🌸</div></div>`;
}

renderHome();setHeader();
